### ISSUE TITLE
Landing Changes

### ISSUE THREAD

**Issue by Nikhil713** [sidharthism/excel2020marketing#37]
The elements in the landing section have to be centered vertically. 

### Current View

![Screenshot_2020-07-14 Excel 2020 Marketing(1)](https://user-images.githubusercontent.com/31701437/87454929-4cecda80-c622-11ea-9749-c4ac36d28def.png)

**Comment by sidharthism** [comment]
Issue was for firefox browser.
Fixed for mozilla firefox.
